slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping

    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan

    use_scan_matching: true
    use_scan_barycenter: true
    do_loop_closing: true
    transform_publish_period: 0.02
    map_update_interval: 1.0
    resolution: 0.05
    min_laser_range: 0.2
    max_laser_range: 8.0
    minimum_time_interval: 0.1
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
    transform_timeout: 0.3
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000

    debug_logging: false
    throttle_scans: 1
    enable_interactive_mode: false

    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
