"""Launch the new triggered OpenClaw goal decision node."""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument('target_points_topic', default_value='/uav/target_points_map'),
        DeclareLaunchArgument('target_markers_topic', default_value='/uav/target_markers'),
        DeclareLaunchArgument('control_topic', default_value='/openclaw_goal/control'),
        DeclareLaunchArgument('selected_goal_topic', default_value='/openclaw_goal/selected_goal'),
        DeclareLaunchArgument('task_goal_topic', default_value='/uav/task_goal'),
        DeclareLaunchArgument('target_order_topic', default_value='/openclaw_goal/target_order'),
        DeclareLaunchArgument('decision_topic', default_value='/openclaw_goal/decision'),
        DeclareLaunchArgument('decision_text_topic', default_value='/openclaw_goal/decision_text'),
        DeclareLaunchArgument('reply_text_topic', default_value='/openclaw_goal/reply_text'),
        DeclareLaunchArgument('mission_status_topic', default_value='/openclaw_goal/mission_status'),
        DeclareLaunchArgument('reached_goal_topic', default_value='/goal_slam_nav/reached_goal'),
        DeclareLaunchArgument('nav_status_topic', default_value='/goal_slam_nav/status'),
        DeclareLaunchArgument('target_frame', default_value='map'),
        DeclareLaunchArgument('base_frames', default_value='base_footprint,base_link'),
        DeclareLaunchArgument('tf_timeout_sec', default_value='0.2'),
        DeclareLaunchArgument('openclaw_base_url', default_value='http://127.0.0.1:18789'),
        DeclareLaunchArgument('openclaw_config_path', default_value='/home/elf/.openclaw/openclaw.json'),
        DeclareLaunchArgument('openclaw_token', default_value=''),
        DeclareLaunchArgument('openclaw_agent_id', default_value='main'),
        DeclareLaunchArgument('openclaw_model', default_value='openclaw'),
        DeclareLaunchArgument('decision_language', default_value='zh_CN'),
        DeclareLaunchArgument('request_timeout_sec', default_value='60.0'),
        DeclareLaunchArgument('min_decision_interval_sec', default_value='1.0'),
        DeclareLaunchArgument('max_targets', default_value='20'),
        DeclareLaunchArgument('class_priority', default_value='red_ball,red_cube'),
        DeclareLaunchArgument('fallback_on_error', default_value='true'),
        DeclareLaunchArgument('send_goal_on_fallback', default_value='false'),
        DeclareLaunchArgument('multi_goal_auto', default_value='true'),
        DeclareLaunchArgument('continuous_auto', default_value='true'),
        DeclareLaunchArgument('continuous_decision_period_sec', default_value='5.0'),
        DeclareLaunchArgument('goal_reached_match_radius_m', default_value='0.60'),
        DeclareLaunchArgument('visited_radius_m', default_value='0.45'),
        DeclareLaunchArgument('debug_log', default_value='false'),
        Node(
            package='car_yolo',
            executable='openclaw_goal_decision_node',
            name='openclaw_goal_decision_node',
            output='screen',
            parameters=[{
                'target_points_topic': LaunchConfiguration('target_points_topic'),
                'target_markers_topic': LaunchConfiguration('target_markers_topic'),
                'control_topic': LaunchConfiguration('control_topic'),
                'selected_goal_topic': LaunchConfiguration('selected_goal_topic'),
                'task_goal_topic': LaunchConfiguration('task_goal_topic'),
                'target_order_topic': LaunchConfiguration('target_order_topic'),
                'decision_topic': LaunchConfiguration('decision_topic'),
                'decision_text_topic': LaunchConfiguration('decision_text_topic'),
                'reply_text_topic': LaunchConfiguration('reply_text_topic'),
                'mission_status_topic': LaunchConfiguration('mission_status_topic'),
                'reached_goal_topic': LaunchConfiguration('reached_goal_topic'),
                'nav_status_topic': LaunchConfiguration('nav_status_topic'),
                'target_frame': LaunchConfiguration('target_frame'),
                'base_frames': LaunchConfiguration('base_frames'),
                'tf_timeout_sec': LaunchConfiguration('tf_timeout_sec'),
                'openclaw_base_url': LaunchConfiguration('openclaw_base_url'),
                'openclaw_config_path': LaunchConfiguration('openclaw_config_path'),
                'openclaw_token': LaunchConfiguration('openclaw_token'),
                'openclaw_agent_id': LaunchConfiguration('openclaw_agent_id'),
                'openclaw_model': LaunchConfiguration('openclaw_model'),
                'decision_language': LaunchConfiguration('decision_language'),
                'request_timeout_sec': LaunchConfiguration('request_timeout_sec'),
                'min_decision_interval_sec': LaunchConfiguration('min_decision_interval_sec'),
                'max_targets': LaunchConfiguration('max_targets'),
                'class_priority': LaunchConfiguration('class_priority'),
                'fallback_on_error': LaunchConfiguration('fallback_on_error'),
                'send_goal_on_fallback': LaunchConfiguration('send_goal_on_fallback'),
                'multi_goal_auto': LaunchConfiguration('multi_goal_auto'),
                'continuous_auto': LaunchConfiguration('continuous_auto'),
                'continuous_decision_period_sec': LaunchConfiguration('continuous_decision_period_sec'),
                'goal_reached_match_radius_m': LaunchConfiguration('goal_reached_match_radius_m'),
                'visited_radius_m': LaunchConfiguration('visited_radius_m'),
                'debug_log': LaunchConfiguration('debug_log'),
            }],
        ),
    ])
